module Evergreen.Migrate.V12 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V10.CalendarDict
import Evergreen.V10.HabitCalendar
import Evergreen.V10.Toggl
import Evergreen.V10.Types
import Evergreen.V12.CalendarDict
import Evergreen.V12.HabitCalendar
import Evergreen.V12.Toggl
import Evergreen.V12.Types
import Lamdera.Migrations exposing (ModelMigration(..), MsgMigration(..))
import SeqDict


frontendModel : Evergreen.V10.Types.FrontendModel -> ModelMigration Evergreen.V12.Types.FrontendModel Evergreen.V12.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V10.Types.BackendModel -> ModelMigration Evergreen.V12.Types.BackendModel Evergreen.V12.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V10.Types.FrontendMsg -> MsgMigration Evergreen.V12.Types.FrontendMsg Evergreen.V12.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V10.Types.ToBackend -> MsgMigration Evergreen.V12.Types.ToBackend Evergreen.V12.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V10.Types.BackendMsg -> MsgMigration Evergreen.V12.Types.BackendMsg Evergreen.V12.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V10.Types.ToFrontend -> MsgMigration Evergreen.V12.Types.ToFrontend Evergreen.V12.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V10.Types.BackendModel -> Evergreen.V12.Types.BackendModel
migrate_Types_BackendModel old =
    { calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglWorkspaces = old.togglWorkspaces |> List.map migrate_Toggl_TogglWorkspace
    , togglProjects = old.togglProjects |> List.map migrate_Toggl_TogglProject
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    , webhookEvents = old.webhookEvents
    }


migrate_Types_FrontendModel : Evergreen.V10.Types.FrontendModel -> Evergreen.V12.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentTime = old.currentTime
    , currentZone = old.currentZone
    , calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglStatus = old.togglStatus |> migrate_Types_TogglConnectionStatus
    , modalState = old.modalState |> migrate_Types_ModalState
    , availableProjects = old.availableProjects |> List.map migrate_Toggl_TogglProject
    , projectsLoading = old.projectsLoading
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    , webhookDebugLog = old.webhookDebugLog
    , stopTimerError = old.stopTimerError
    }


migrate_CalendarDict_CalendarDict : Evergreen.V10.CalendarDict.CalendarDict -> Evergreen.V12.CalendarDict.CalendarDict
migrate_CalendarDict_CalendarDict old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_HabitCalendar_HabitCalendarId migrate_HabitCalendar_HabitCalendar) |> SeqDict.fromList


migrate_HabitCalendar_HabitCalendar : Evergreen.V10.HabitCalendar.HabitCalendar -> Evergreen.V12.HabitCalendar.HabitCalendar
migrate_HabitCalendar_HabitCalendar old =
    { id = old.id |> migrate_HabitCalendar_HabitCalendarId
    , name = old.name
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , weeksShowing = old.weeksShowing
    , entries = old.entries
    , timeEntries = old.timeEntries |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Toggl_TimeEntryId migrate_Toggl_TimeEntry) |> SeqDict.fromList
    , timezone = old.timezone
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , projectId = old.projectId |> migrate_Toggl_TogglProjectId
    , isOrangetheory = False
    }


migrate_HabitCalendar_HabitCalendarId : Evergreen.V10.HabitCalendar.HabitCalendarId -> Evergreen.V12.HabitCalendar.HabitCalendarId
migrate_HabitCalendar_HabitCalendarId old =
    case old of
        Evergreen.V10.HabitCalendar.HabitCalendarId p0 ->
            Evergreen.V12.HabitCalendar.HabitCalendarId p0


migrate_Toggl_TimeEntry : Evergreen.V10.Toggl.TimeEntry -> Evergreen.V12.Toggl.TimeEntry
migrate_Toggl_TimeEntry old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Toggl_TimeEntryId : Evergreen.V10.Toggl.TimeEntryId -> Evergreen.V12.Toggl.TimeEntryId
migrate_Toggl_TimeEntryId old =
    case old of
        Evergreen.V10.Toggl.TimeEntryId p0 ->
            Evergreen.V12.Toggl.TimeEntryId p0


migrate_Toggl_TogglApiError : Evergreen.V10.Toggl.TogglApiError -> Evergreen.V12.Toggl.TogglApiError
migrate_Toggl_TogglApiError old =
    case old of
        Evergreen.V10.Toggl.HttpError p0 ->
            Evergreen.V12.Toggl.HttpError p0

        Evergreen.V10.Toggl.RateLimited p0 ->
            Evergreen.V12.Toggl.RateLimited p0


migrate_Toggl_TogglProject : Evergreen.V10.Toggl.TogglProject -> Evergreen.V12.Toggl.TogglProject
migrate_Toggl_TogglProject old =
    { id = old.id |> migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , color = old.color
    }


migrate_Toggl_TogglProjectId : Evergreen.V10.Toggl.TogglProjectId -> Evergreen.V12.Toggl.TogglProjectId
migrate_Toggl_TogglProjectId old =
    case old of
        Evergreen.V10.Toggl.TogglProjectId p0 ->
            Evergreen.V12.Toggl.TogglProjectId p0


migrate_Toggl_TogglWorkspace : Evergreen.V10.Toggl.TogglWorkspace -> Evergreen.V12.Toggl.TogglWorkspace
migrate_Toggl_TogglWorkspace old =
    { id = old.id |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , organizationId = old.organizationId
    }


migrate_Toggl_TogglWorkspaceId : Evergreen.V10.Toggl.TogglWorkspaceId -> Evergreen.V12.Toggl.TogglWorkspaceId
migrate_Toggl_TogglWorkspaceId old =
    case old of
        Evergreen.V10.Toggl.TogglWorkspaceId p0 ->
            Evergreen.V12.Toggl.TogglWorkspaceId p0


migrate_Toggl_WebhookPayload : Evergreen.V10.Toggl.WebhookPayload -> Evergreen.V12.Toggl.WebhookPayload
migrate_Toggl_WebhookPayload old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Types_BackendMsg : Evergreen.V10.Types.BackendMsg -> Evergreen.V12.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V10.Types.NoOpBackendMsg ->
            Evergreen.V12.Types.NoOpBackendMsg

        Evergreen.V10.Types.ClientConnected p0 p1 ->
            Evergreen.V12.Types.ClientConnected p0 p1

        Evergreen.V10.Types.ClientDisconnected p0 p1 ->
            Evergreen.V12.Types.ClientDisconnected p0 p1

        Evergreen.V10.Types.GotTogglWorkspaces p0 p1 ->
            Evergreen.V12.Types.GotTogglWorkspaces p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V10.Types.GotTogglProjects p0 p1 ->
            Evergreen.V12.Types.GotTogglProjects p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V10.Types.GotTogglTimeEntries p0 p1 p2 p3 p4 p5 ->
            Evergreen.V12.Types.GotTogglTimeEntries p0
                (p1 |> migrate_Types_CalendarInfo)
                (p2 |> migrate_Toggl_TogglWorkspaceId)
                (p3 |> migrate_Toggl_TogglProjectId)
                p4
                (p5 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TimeEntry))

        Evergreen.V10.Types.GotWebhookValidation p0 ->
            Evergreen.V12.Types.GotWebhookValidation p0

        Evergreen.V10.Types.GotStopTimerResponse p0 p1 ->
            Evergreen.V12.Types.GotStopTimerResponse p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError)

        Evergreen.V10.Types.BroadcastRunningEntry p0 ->
            Evergreen.V12.Types.BroadcastRunningEntry (p0 |> migrate_Types_RunningEntry)


migrate_Types_CalendarInfo : Evergreen.V10.Types.CalendarInfo -> Evergreen.V12.Types.CalendarInfo
migrate_Types_CalendarInfo old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = False
    }


migrate_Types_CreateCalendarModal : Evergreen.V10.Types.CreateCalendarModal -> Evergreen.V12.Types.CreateCalendarModal
migrate_Types_CreateCalendarModal old =
    { selectedWorkspace = old.selectedWorkspace |> Maybe.map migrate_Toggl_TogglWorkspace
    , selectedProject = old.selectedProject |> Maybe.map migrate_Toggl_TogglProject
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = False
    }


migrate_Types_EditCalendarModal : Evergreen.V10.Types.EditCalendarModal -> Evergreen.V12.Types.EditCalendarModal
migrate_Types_EditCalendarModal old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , originalProjectId = old.originalProjectId |> migrate_Toggl_TogglProjectId
    , selectedWorkspace = old.selectedWorkspace |> migrate_Toggl_TogglWorkspace
    , selectedProject = old.selectedProject |> migrate_Toggl_TogglProject
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = False
    }


migrate_Types_FrontendMsg : Evergreen.V10.Types.FrontendMsg -> Evergreen.V12.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V10.Types.UrlClicked p0 ->
            Evergreen.V12.Types.UrlClicked p0

        Evergreen.V10.Types.UrlChanged p0 ->
            Evergreen.V12.Types.UrlChanged p0

        Evergreen.V10.Types.NoOpFrontendMsg ->
            Evergreen.V12.Types.NoOpFrontendMsg

        Evergreen.V10.Types.GotTime p0 ->
            Evergreen.V12.Types.GotTime p0

        Evergreen.V10.Types.GotZone p0 ->
            Evergreen.V12.Types.GotZone p0

        Evergreen.V10.Types.Tick p0 ->
            Evergreen.V12.Types.Tick p0

        Evergreen.V10.Types.RefreshWorkspaces ->
            Evergreen.V12.Types.RefreshWorkspaces

        Evergreen.V10.Types.RefreshCalendar p0 p1 p2 p3 ->
            Evergreen.V12.Types.RefreshCalendar (p0 |> migrate_HabitCalendar_HabitCalendarId)
                (p1 |> migrate_Toggl_TogglWorkspaceId)
                (p2 |> migrate_Toggl_TogglProjectId)
                p3

        Evergreen.V10.Types.OpenCreateCalendarModal ->
            Evergreen.V12.Types.OpenCreateCalendarModal

        Evergreen.V10.Types.CloseModal ->
            Evergreen.V12.Types.CloseModal

        Evergreen.V10.Types.SelectWorkspace p0 ->
            Evergreen.V12.Types.SelectWorkspace (p0 |> migrate_Toggl_TogglWorkspace)

        Evergreen.V10.Types.SelectProject p0 ->
            Evergreen.V12.Types.SelectProject (p0 |> migrate_Toggl_TogglProject)

        Evergreen.V10.Types.CalendarNameChanged p0 ->
            Evergreen.V12.Types.CalendarNameChanged p0

        Evergreen.V10.Types.SuccessColorChanged p0 ->
            Evergreen.V12.Types.SuccessColorChanged p0

        Evergreen.V10.Types.NonzeroColorChanged p0 ->
            Evergreen.V12.Types.NonzeroColorChanged p0

        Evergreen.V10.Types.SubmitCreateCalendar ->
            Evergreen.V12.Types.SubmitCreateCalendar

        Evergreen.V10.Types.OpenEditCalendarModal p0 ->
            Evergreen.V12.Types.OpenEditCalendarModal (p0 |> migrate_HabitCalendar_HabitCalendar)

        Evergreen.V10.Types.EditCalendarSelectWorkspace p0 ->
            Evergreen.V12.Types.EditCalendarSelectWorkspace (p0 |> migrate_Toggl_TogglWorkspace)

        Evergreen.V10.Types.EditCalendarSelectProject p0 ->
            Evergreen.V12.Types.EditCalendarSelectProject (p0 |> migrate_Toggl_TogglProject)

        Evergreen.V10.Types.EditCalendarNameChanged p0 ->
            Evergreen.V12.Types.EditCalendarNameChanged p0

        Evergreen.V10.Types.EditSuccessColorChanged p0 ->
            Evergreen.V12.Types.EditSuccessColorChanged p0

        Evergreen.V10.Types.EditNonzeroColorChanged p0 ->
            Evergreen.V12.Types.EditNonzeroColorChanged p0

        Evergreen.V10.Types.SubmitEditCalendar ->
            Evergreen.V12.Types.SubmitEditCalendar

        Evergreen.V10.Types.DeleteCalendar p0 ->
            Evergreen.V12.Types.DeleteCalendar (p0 |> migrate_HabitCalendar_HabitCalendarId)

        Evergreen.V10.Types.StopRunningTimer ->
            Evergreen.V12.Types.StopRunningTimer

        Evergreen.V10.Types.DismissStopTimerError ->
            Evergreen.V12.Types.DismissStopTimerError

        Evergreen.V10.Types.ClearWebhookEvents ->
            Evergreen.V12.Types.ClearWebhookEvents


migrate_Types_ModalState : Evergreen.V10.Types.ModalState -> Evergreen.V12.Types.ModalState
migrate_Types_ModalState old =
    case old of
        Evergreen.V10.Types.ModalClosed ->
            Evergreen.V12.Types.ModalClosed

        Evergreen.V10.Types.ModalCreateCalendar p0 ->
            Evergreen.V12.Types.ModalCreateCalendar (p0 |> migrate_Types_CreateCalendarModal)

        Evergreen.V10.Types.ModalEditCalendar p0 ->
            Evergreen.V12.Types.ModalEditCalendar (p0 |> migrate_Types_EditCalendarModal)


migrate_Types_RunningEntry : Evergreen.V10.Types.RunningEntry -> Evergreen.V12.Types.RunningEntry
migrate_Types_RunningEntry old =
    case old of
        Evergreen.V10.Types.NoRunningEntry ->
            Evergreen.V12.Types.NoRunningEntry

        Evergreen.V10.Types.RunningEntry p0 ->
            Evergreen.V12.Types.RunningEntry (p0 |> migrate_Toggl_WebhookPayload)


migrate_Types_ToBackend : Evergreen.V10.Types.ToBackend -> Evergreen.V12.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V10.Types.NoOpToBackend ->
            Evergreen.V12.Types.NoOpToBackend

        Evergreen.V10.Types.RequestCalendars ->
            Evergreen.V12.Types.RequestCalendars

        Evergreen.V10.Types.FetchTogglWorkspaces ->
            Evergreen.V12.Types.FetchTogglWorkspaces

        Evergreen.V10.Types.FetchTogglProjects p0 ->
            Evergreen.V12.Types.FetchTogglProjects (p0 |> migrate_Toggl_TogglWorkspaceId)

        Evergreen.V10.Types.FetchTogglTimeEntries p0 p1 p2 p3 p4 p5 ->
            Evergreen.V12.Types.FetchTogglTimeEntries (p0 |> migrate_Types_CalendarInfo)
                (p1 |> migrate_Toggl_TogglWorkspaceId)
                (p2 |> migrate_Toggl_TogglProjectId)
                p3
                p4
                p5

        Evergreen.V10.Types.StopTogglTimer p0 p1 ->
            Evergreen.V12.Types.StopTogglTimer (p0 |> migrate_Toggl_TogglWorkspaceId)
                (p1 |> migrate_Toggl_TimeEntryId)

        Evergreen.V10.Types.ClearWebhookEventsRequest ->
            Evergreen.V12.Types.ClearWebhookEventsRequest

        Evergreen.V10.Types.UpdateCalendar p0 p1 p2 p3 p4 p5 ->
            Evergreen.V12.Types.UpdateCalendar (p0 |> migrate_HabitCalendar_HabitCalendarId)
                p1
                (p2 |> migrate_Toggl_TogglWorkspaceId)
                (p3 |> migrate_Toggl_TogglProjectId)
                p4
                p5
                False

        Evergreen.V10.Types.DeleteCalendarRequest p0 ->
            Evergreen.V12.Types.DeleteCalendarRequest (p0 |> migrate_HabitCalendar_HabitCalendarId)


migrate_Types_ToFrontend : Evergreen.V10.Types.ToFrontend -> Evergreen.V12.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V10.Types.NoOpToFrontend ->
            Evergreen.V12.Types.NoOpToFrontend

        Evergreen.V10.Types.CalendarsUpdated p0 ->
            Evergreen.V12.Types.CalendarsUpdated (p0 |> migrate_CalendarDict_CalendarDict)

        Evergreen.V10.Types.TogglWorkspacesReceived p0 ->
            Evergreen.V12.Types.TogglWorkspacesReceived (p0 |> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V10.Types.TogglProjectsReceived p0 ->
            Evergreen.V12.Types.TogglProjectsReceived (p0 |> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V10.Types.TogglTimeEntriesReceived p0 ->
            Evergreen.V12.Types.TogglTimeEntriesReceived (p0 |> Result.map (List.map migrate_Toggl_TimeEntry))

        Evergreen.V10.Types.RunningEntryUpdated p0 ->
            Evergreen.V12.Types.RunningEntryUpdated (p0 |> migrate_Types_RunningEntry)

        Evergreen.V10.Types.WebhookDebugEvent p0 ->
            Evergreen.V12.Types.WebhookDebugEvent (p0 |> migrate_Types_WebhookDebugEntry)

        Evergreen.V10.Types.WebhookEventsCleared ->
            Evergreen.V12.Types.WebhookEventsCleared

        Evergreen.V10.Types.StopTimerFailed p0 p1 ->
            Evergreen.V12.Types.StopTimerFailed p0 (p1 |> migrate_Types_RunningEntry)


migrate_Types_TogglConnectionStatus : Evergreen.V10.Types.TogglConnectionStatus -> Evergreen.V12.Types.TogglConnectionStatus
migrate_Types_TogglConnectionStatus old =
    case old of
        Evergreen.V10.Types.NotConnected ->
            Evergreen.V12.Types.NotConnected

        Evergreen.V10.Types.Connecting ->
            Evergreen.V12.Types.Connecting

        Evergreen.V10.Types.Connected p0 ->
            Evergreen.V12.Types.Connected (p0 |> List.map migrate_Toggl_TogglWorkspace)

        Evergreen.V10.Types.ConnectionError p0 ->
            Evergreen.V12.Types.ConnectionError p0


migrate_Types_WebhookDebugEntry : Evergreen.V10.Types.WebhookDebugEntry -> Evergreen.V12.Types.WebhookDebugEntry
migrate_Types_WebhookDebugEntry old =
    old
