module Evergreen.Migrate.V13 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V12.CalendarDict
import Evergreen.V12.HabitCalendar
import Evergreen.V12.Toggl
import Evergreen.V12.Types
import Evergreen.V13.CalendarDict
import Evergreen.V13.HabitCalendar
import Evergreen.V13.Toggl
import Evergreen.V13.Types
import Lamdera.Migrations exposing (ModelMigration(..), MsgMigration(..))
import SeqDict


frontendModel : Evergreen.V12.Types.FrontendModel -> ModelMigration Evergreen.V13.Types.FrontendModel Evergreen.V13.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V12.Types.BackendModel -> ModelMigration Evergreen.V13.Types.BackendModel Evergreen.V13.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V12.Types.FrontendMsg -> MsgMigration Evergreen.V13.Types.FrontendMsg Evergreen.V13.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V12.Types.ToBackend -> MsgMigration Evergreen.V13.Types.ToBackend Evergreen.V13.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V12.Types.BackendMsg -> MsgMigration Evergreen.V13.Types.BackendMsg Evergreen.V13.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V12.Types.ToFrontend -> MsgMigration Evergreen.V13.Types.ToFrontend Evergreen.V13.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V12.Types.FrontendModel -> Evergreen.V13.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentTime = old.currentTime
    , currentZone = old.currentZone
    , calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglStatus = old.togglStatus |> migrate_Types_TogglConnectionStatus
    , modalState = old.modalState |> migrate_Types_ModalState
    , availableProjects = old.availableProjects |> List.map migrate_Toggl_TogglProject
    , projectsLoading = old.projectsLoading
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    , webhookDebugLog = old.webhookDebugLog
    , stopTimerError = old.stopTimerError
    }


migrate_CalendarDict_CalendarDict : Evergreen.V12.CalendarDict.CalendarDict -> Evergreen.V13.CalendarDict.CalendarDict
migrate_CalendarDict_CalendarDict old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_HabitCalendar_HabitCalendarId migrate_HabitCalendar_HabitCalendar) |> SeqDict.fromList


migrate_HabitCalendar_HabitCalendar : Evergreen.V12.HabitCalendar.HabitCalendar -> Evergreen.V13.HabitCalendar.HabitCalendar
migrate_HabitCalendar_HabitCalendar old =
    { id = old.id |> migrate_HabitCalendar_HabitCalendarId
    , name = old.name
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , weeksShowing = old.weeksShowing
    , entries = old.entries
    , timeEntries = old.timeEntries |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Toggl_TimeEntryId migrate_Toggl_TimeEntry) |> SeqDict.fromList
    , timezone = old.timezone
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , projectId = old.projectId |> migrate_Toggl_TogglProjectId
    , isOrangetheory = old.isOrangetheory
    }


migrate_HabitCalendar_HabitCalendarId : Evergreen.V12.HabitCalendar.HabitCalendarId -> Evergreen.V13.HabitCalendar.HabitCalendarId
migrate_HabitCalendar_HabitCalendarId old =
    case old of
        Evergreen.V12.HabitCalendar.HabitCalendarId p0 ->
            Evergreen.V13.HabitCalendar.HabitCalendarId p0


migrate_Toggl_TimeEntry : Evergreen.V12.Toggl.TimeEntry -> Evergreen.V13.Toggl.TimeEntry
migrate_Toggl_TimeEntry old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Toggl_TimeEntryId : Evergreen.V12.Toggl.TimeEntryId -> Evergreen.V13.Toggl.TimeEntryId
migrate_Toggl_TimeEntryId old =
    case old of
        Evergreen.V12.Toggl.TimeEntryId p0 ->
            Evergreen.V13.Toggl.TimeEntryId p0


migrate_Toggl_TogglProject : Evergreen.V12.Toggl.TogglProject -> Evergreen.V13.Toggl.TogglProject
migrate_Toggl_TogglProject old =
    { id = old.id |> migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , color = old.color
    }


migrate_Toggl_TogglProjectId : Evergreen.V12.Toggl.TogglProjectId -> Evergreen.V13.Toggl.TogglProjectId
migrate_Toggl_TogglProjectId old =
    case old of
        Evergreen.V12.Toggl.TogglProjectId p0 ->
            Evergreen.V13.Toggl.TogglProjectId p0


migrate_Toggl_TogglWorkspace : Evergreen.V12.Toggl.TogglWorkspace -> Evergreen.V13.Toggl.TogglWorkspace
migrate_Toggl_TogglWorkspace old =
    { id = old.id |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , organizationId = old.organizationId
    }


migrate_Toggl_TogglWorkspaceId : Evergreen.V12.Toggl.TogglWorkspaceId -> Evergreen.V13.Toggl.TogglWorkspaceId
migrate_Toggl_TogglWorkspaceId old =
    case old of
        Evergreen.V12.Toggl.TogglWorkspaceId p0 ->
            Evergreen.V13.Toggl.TogglWorkspaceId p0


migrate_Toggl_WebhookPayload : Evergreen.V12.Toggl.WebhookPayload -> Evergreen.V13.Toggl.WebhookPayload
migrate_Toggl_WebhookPayload old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Types_CreateCalendarModal : Evergreen.V12.Types.CreateCalendarModal -> Evergreen.V13.Types.CreateCalendarModal
migrate_Types_CreateCalendarModal old =
    { selectedWorkspace = old.selectedWorkspace |> Maybe.map migrate_Toggl_TogglWorkspace
    , selectedProject = old.selectedProject |> Maybe.map migrate_Toggl_TogglProject
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = old.isOrangetheory
    , projectFilter = ""
    }


migrate_Types_EditCalendarModal : Evergreen.V12.Types.EditCalendarModal -> Evergreen.V13.Types.EditCalendarModal
migrate_Types_EditCalendarModal old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , originalProjectId = old.originalProjectId |> migrate_Toggl_TogglProjectId
    , selectedWorkspace = old.selectedWorkspace |> migrate_Toggl_TogglWorkspace
    , selectedProject = old.selectedProject |> migrate_Toggl_TogglProject
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = old.isOrangetheory
    , projectFilter = ""
    }


migrate_Types_FrontendMsg : Evergreen.V12.Types.FrontendMsg -> Evergreen.V13.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V12.Types.UrlClicked p0 ->
            Evergreen.V13.Types.UrlClicked p0

        Evergreen.V12.Types.UrlChanged p0 ->
            Evergreen.V13.Types.UrlChanged p0

        Evergreen.V12.Types.NoOpFrontendMsg ->
            Evergreen.V13.Types.NoOpFrontendMsg

        Evergreen.V12.Types.GotTime p0 ->
            Evergreen.V13.Types.GotTime p0

        Evergreen.V12.Types.GotZone p0 ->
            Evergreen.V13.Types.GotZone p0

        Evergreen.V12.Types.Tick p0 ->
            Evergreen.V13.Types.Tick p0

        Evergreen.V12.Types.RefreshWorkspaces ->
            Evergreen.V13.Types.RefreshWorkspaces

        Evergreen.V12.Types.RefreshCalendar p0 p1 p2 p3 ->
            Evergreen.V13.Types.RefreshCalendar (p0 |> migrate_HabitCalendar_HabitCalendarId)
                (p1 |> migrate_Toggl_TogglWorkspaceId)
                (p2 |> migrate_Toggl_TogglProjectId)
                p3

        Evergreen.V12.Types.OpenCreateCalendarModal ->
            Evergreen.V13.Types.OpenCreateCalendarModal

        Evergreen.V12.Types.CloseModal ->
            Evergreen.V13.Types.CloseModal

        Evergreen.V12.Types.SelectWorkspace p0 ->
            Evergreen.V13.Types.SelectWorkspace (p0 |> migrate_Toggl_TogglWorkspace)

        Evergreen.V12.Types.SelectProject p0 ->
            Evergreen.V13.Types.SelectProject (p0 |> migrate_Toggl_TogglProject)

        Evergreen.V12.Types.CalendarNameChanged p0 ->
            Evergreen.V13.Types.CalendarNameChanged p0

        Evergreen.V12.Types.SuccessColorChanged p0 ->
            Evergreen.V13.Types.SuccessColorChanged p0

        Evergreen.V12.Types.NonzeroColorChanged p0 ->
            Evergreen.V13.Types.NonzeroColorChanged p0

        Evergreen.V12.Types.OrangetheoryToggled p0 ->
            Evergreen.V13.Types.OrangetheoryToggled p0

        Evergreen.V12.Types.SubmitCreateCalendar ->
            Evergreen.V13.Types.SubmitCreateCalendar

        Evergreen.V12.Types.OpenEditCalendarModal p0 ->
            Evergreen.V13.Types.OpenEditCalendarModal (p0 |> migrate_HabitCalendar_HabitCalendar)

        Evergreen.V12.Types.EditCalendarSelectWorkspace p0 ->
            Evergreen.V13.Types.EditCalendarSelectWorkspace (p0 |> migrate_Toggl_TogglWorkspace)

        Evergreen.V12.Types.EditCalendarSelectProject p0 ->
            Evergreen.V13.Types.EditCalendarSelectProject (p0 |> migrate_Toggl_TogglProject)

        Evergreen.V12.Types.EditCalendarNameChanged p0 ->
            Evergreen.V13.Types.EditCalendarNameChanged p0

        Evergreen.V12.Types.EditSuccessColorChanged p0 ->
            Evergreen.V13.Types.EditSuccessColorChanged p0

        Evergreen.V12.Types.EditNonzeroColorChanged p0 ->
            Evergreen.V13.Types.EditNonzeroColorChanged p0

        Evergreen.V12.Types.EditOrangetheoryToggled p0 ->
            Evergreen.V13.Types.EditOrangetheoryToggled p0

        Evergreen.V12.Types.SubmitEditCalendar ->
            Evergreen.V13.Types.SubmitEditCalendar

        Evergreen.V12.Types.DeleteCalendar p0 ->
            Evergreen.V13.Types.DeleteCalendar (p0 |> migrate_HabitCalendar_HabitCalendarId)

        Evergreen.V12.Types.StopRunningTimer ->
            Evergreen.V13.Types.StopRunningTimer

        Evergreen.V12.Types.DismissStopTimerError ->
            Evergreen.V13.Types.DismissStopTimerError

        Evergreen.V12.Types.ClearWebhookEvents ->
            Evergreen.V13.Types.ClearWebhookEvents


migrate_Types_ModalState : Evergreen.V12.Types.ModalState -> Evergreen.V13.Types.ModalState
migrate_Types_ModalState old =
    case old of
        Evergreen.V12.Types.ModalClosed ->
            Evergreen.V13.Types.ModalClosed

        Evergreen.V12.Types.ModalCreateCalendar p0 ->
            Evergreen.V13.Types.ModalCreateCalendar (p0 |> migrate_Types_CreateCalendarModal)

        Evergreen.V12.Types.ModalEditCalendar p0 ->
            Evergreen.V13.Types.ModalEditCalendar (p0 |> migrate_Types_EditCalendarModal)


migrate_Types_RunningEntry : Evergreen.V12.Types.RunningEntry -> Evergreen.V13.Types.RunningEntry
migrate_Types_RunningEntry old =
    case old of
        Evergreen.V12.Types.NoRunningEntry ->
            Evergreen.V13.Types.NoRunningEntry

        Evergreen.V12.Types.RunningEntry p0 ->
            Evergreen.V13.Types.RunningEntry (p0 |> migrate_Toggl_WebhookPayload)


migrate_Types_TogglConnectionStatus : Evergreen.V12.Types.TogglConnectionStatus -> Evergreen.V13.Types.TogglConnectionStatus
migrate_Types_TogglConnectionStatus old =
    case old of
        Evergreen.V12.Types.NotConnected ->
            Evergreen.V13.Types.NotConnected

        Evergreen.V12.Types.Connecting ->
            Evergreen.V13.Types.Connecting

        Evergreen.V12.Types.Connected p0 ->
            Evergreen.V13.Types.Connected (p0 |> List.map migrate_Toggl_TogglWorkspace)

        Evergreen.V12.Types.ConnectionError p0 ->
            Evergreen.V13.Types.ConnectionError p0
