module Evergreen.Migrate.V17 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V16.HabitCalendar
import Evergreen.V16.Toggl
import Evergreen.V16.Types
import Evergreen.V17.HabitCalendar
import Evergreen.V17.Toggl
import Evergreen.V17.Types
import Lamdera.Migrations exposing (ModelMigration(..), MsgMigration(..))


frontendModel : Evergreen.V16.Types.FrontendModel -> ModelMigration Evergreen.V17.Types.FrontendModel Evergreen.V17.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V16.Types.BackendModel -> ModelMigration Evergreen.V17.Types.BackendModel Evergreen.V17.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V16.Types.FrontendMsg -> MsgMigration Evergreen.V17.Types.FrontendMsg Evergreen.V17.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V16.Types.ToBackend -> MsgMigration Evergreen.V17.Types.ToBackend Evergreen.V17.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V16.Types.BackendMsg -> MsgMigration Evergreen.V17.Types.BackendMsg Evergreen.V17.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V16.Types.ToFrontend -> MsgMigration Evergreen.V17.Types.ToFrontend Evergreen.V17.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_HabitCalendar_HabitCalendarId : Evergreen.V16.HabitCalendar.HabitCalendarId -> Evergreen.V17.HabitCalendar.HabitCalendarId
migrate_HabitCalendar_HabitCalendarId old =
    case old of
        Evergreen.V16.HabitCalendar.HabitCalendarId p0 ->
            Evergreen.V17.HabitCalendar.HabitCalendarId p0


migrate_Toggl_TimeEntry : Evergreen.V16.Toggl.TimeEntry -> Evergreen.V17.Toggl.TimeEntry
migrate_Toggl_TimeEntry old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Toggl_TimeEntryId : Evergreen.V16.Toggl.TimeEntryId -> Evergreen.V17.Toggl.TimeEntryId
migrate_Toggl_TimeEntryId old =
    case old of
        Evergreen.V16.Toggl.TimeEntryId p0 ->
            Evergreen.V17.Toggl.TimeEntryId p0


migrate_Toggl_TogglApiError : Evergreen.V16.Toggl.TogglApiError -> Evergreen.V17.Toggl.TogglApiError
migrate_Toggl_TogglApiError old =
    case old of
        Evergreen.V16.Toggl.HttpError p0 ->
            Evergreen.V17.Toggl.HttpError p0

        Evergreen.V16.Toggl.RateLimited p0 ->
            Evergreen.V17.Toggl.RateLimited p0


migrate_Toggl_TogglProject : Evergreen.V16.Toggl.TogglProject -> Evergreen.V17.Toggl.TogglProject
migrate_Toggl_TogglProject old =
    { id = old.id |> migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , color = old.color
    }


migrate_Toggl_TogglProjectId : Evergreen.V16.Toggl.TogglProjectId -> Evergreen.V17.Toggl.TogglProjectId
migrate_Toggl_TogglProjectId old =
    case old of
        Evergreen.V16.Toggl.TogglProjectId p0 ->
            Evergreen.V17.Toggl.TogglProjectId p0


migrate_Toggl_TogglWorkspace : Evergreen.V16.Toggl.TogglWorkspace -> Evergreen.V17.Toggl.TogglWorkspace
migrate_Toggl_TogglWorkspace old =
    { id = old.id |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , organizationId = old.organizationId
    }


migrate_Toggl_TogglWorkspaceId : Evergreen.V16.Toggl.TogglWorkspaceId -> Evergreen.V17.Toggl.TogglWorkspaceId
migrate_Toggl_TogglWorkspaceId old =
    case old of
        Evergreen.V16.Toggl.TogglWorkspaceId p0 ->
            Evergreen.V17.Toggl.TogglWorkspaceId p0


migrate_Toggl_WebhookPayload : Evergreen.V16.Toggl.WebhookPayload -> Evergreen.V17.Toggl.WebhookPayload
migrate_Toggl_WebhookPayload old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Types_BackendMsg : Evergreen.V16.Types.BackendMsg -> Evergreen.V17.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V16.Types.NoOpBackendMsg ->
            Evergreen.V17.Types.NoOpBackendMsg

        Evergreen.V16.Types.ClientConnected p0 p1 ->
            Evergreen.V17.Types.ClientConnected p0 p1

        Evergreen.V16.Types.ClientDisconnected p0 p1 ->
            Evergreen.V17.Types.ClientDisconnected p0 p1

        Evergreen.V16.Types.GotTogglWorkspaces p0 p1 ->
            Evergreen.V17.Types.GotTogglWorkspaces p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V16.Types.GotTogglProjects p0 p1 ->
            Evergreen.V17.Types.GotTogglProjects p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V16.Types.GotTogglTimeEntries p0 p1 p2 p3 p4 p5 ->
            Evergreen.V17.Types.GotTogglTimeEntries p0
                (p1 |> migrate_Types_CalendarInfo)
                (p2 |> migrate_Toggl_TogglWorkspaceId)
                (p3 |> migrate_Toggl_TogglProjectId)
                p4
                (p5 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TimeEntry))

        Evergreen.V16.Types.GotWebhookValidation p0 ->
            Evergreen.V17.Types.GotWebhookValidation p0

        Evergreen.V16.Types.GotStopTimerResponse p0 p1 ->
            Evergreen.V17.Types.GotStopTimerResponse p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError)

        Evergreen.V16.Types.BroadcastRunningEntry p0 ->
            Evergreen.V17.Types.BroadcastRunningEntry (p0 |> migrate_Types_RunningEntry)

        Evergreen.V16.Types.CodaPollTick p0 ->
            Evergreen.V17.Types.CodaPollTick p0

        Evergreen.V16.Types.GotCodaResponse p0 ->
            Evergreen.V17.Types.GotCodaResponse p0

        Evergreen.V16.Types.StartTimerWithTime p0 p1 p2 ->
            Evergreen.V17.Types.StartTimerWithTime p0 p1 p2

        Evergreen.V16.Types.GotStartTimerResponse p0 p1 ->
            Evergreen.V17.Types.GotStartTimerResponse p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError)


migrate_Types_CalendarInfo : Evergreen.V16.Types.CalendarInfo -> Evergreen.V17.Types.CalendarInfo
migrate_Types_CalendarInfo old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = old.isOrangetheory
    }


migrate_Types_RunningEntry : Evergreen.V16.Types.RunningEntry -> Evergreen.V17.Types.RunningEntry
migrate_Types_RunningEntry old =
    case old of
        Evergreen.V16.Types.NoRunningEntry ->
            Evergreen.V17.Types.NoRunningEntry

        Evergreen.V16.Types.RunningEntry p0 ->
            Evergreen.V17.Types.RunningEntry (p0 |> migrate_Toggl_WebhookPayload)
