module Evergreen.Migrate.V19 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V17.CalendarDict
import Evergreen.V17.HabitCalendar
import Evergreen.V17.Toggl
import Evergreen.V17.Types
import Evergreen.V19.CalendarDict
import Evergreen.V19.HabitCalendar
import Evergreen.V19.Toggl
import Evergreen.V19.Types
import Lamdera.Migrations exposing (ModelMigration(..), MsgMigration(..))
import SeqDict


frontendModel : Evergreen.V17.Types.FrontendModel -> ModelMigration Evergreen.V19.Types.FrontendModel Evergreen.V19.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V17.Types.BackendModel -> ModelMigration Evergreen.V19.Types.BackendModel Evergreen.V19.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V17.Types.FrontendMsg -> MsgMigration Evergreen.V19.Types.FrontendMsg Evergreen.V19.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V17.Types.ToBackend -> MsgMigration Evergreen.V19.Types.ToBackend Evergreen.V19.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V17.Types.BackendMsg -> MsgMigration Evergreen.V19.Types.BackendMsg Evergreen.V19.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V17.Types.ToFrontend -> MsgMigration Evergreen.V19.Types.ToFrontend Evergreen.V19.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V17.Types.BackendModel -> Evergreen.V19.Types.BackendModel
migrate_Types_BackendModel old =
    { calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglWorkspaces = old.togglWorkspaces |> List.map migrate_Toggl_TogglWorkspace
    , togglProjects = old.togglProjects |> List.map migrate_Toggl_TogglProject
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    , webhookEvents = old.webhookEvents
    , monofocusStatus = Evergreen.V19.Types.MonofocusNotFetched
    }


migrate_Types_FrontendModel : Evergreen.V17.Types.FrontendModel -> Evergreen.V19.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentTime = old.currentTime
    , currentZone = old.currentZone
    , calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglStatus = old.togglStatus |> migrate_Types_TogglConnectionStatus
    , modalState = old.modalState |> migrate_Types_ModalState
    , availableProjects = old.availableProjects |> List.map migrate_Toggl_TogglProject
    , projectsLoading = old.projectsLoading
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    , webhookDebugLog = old.webhookDebugLog
    , stopTimerError = old.stopTimerError
    , monofocusStatus = Evergreen.V19.Types.MonofocusNotFetched
    , startMonofocusTimerError = old.startMonofocusTimerError
    }


migrate_CalendarDict_CalendarDict : Evergreen.V17.CalendarDict.CalendarDict -> Evergreen.V19.CalendarDict.CalendarDict
migrate_CalendarDict_CalendarDict old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_HabitCalendar_HabitCalendarId migrate_HabitCalendar_HabitCalendar) |> SeqDict.fromList


migrate_HabitCalendar_HabitCalendar : Evergreen.V17.HabitCalendar.HabitCalendar -> Evergreen.V19.HabitCalendar.HabitCalendar
migrate_HabitCalendar_HabitCalendar old =
    { id = old.id |> migrate_HabitCalendar_HabitCalendarId
    , name = old.name
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , weeksShowing = old.weeksShowing
    , entries = old.entries
    , timeEntries = old.timeEntries |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Toggl_TimeEntryId migrate_Toggl_TimeEntry) |> SeqDict.fromList
    , timezone = old.timezone
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , projectId = old.projectId |> migrate_Toggl_TogglProjectId
    , isOrangetheory = old.isOrangetheory
    }


migrate_HabitCalendar_HabitCalendarId : Evergreen.V17.HabitCalendar.HabitCalendarId -> Evergreen.V19.HabitCalendar.HabitCalendarId
migrate_HabitCalendar_HabitCalendarId old =
    case old of
        Evergreen.V17.HabitCalendar.HabitCalendarId p0 ->
            Evergreen.V19.HabitCalendar.HabitCalendarId p0


migrate_Toggl_TimeEntry : Evergreen.V17.Toggl.TimeEntry -> Evergreen.V19.Toggl.TimeEntry
migrate_Toggl_TimeEntry old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Toggl_TimeEntryId : Evergreen.V17.Toggl.TimeEntryId -> Evergreen.V19.Toggl.TimeEntryId
migrate_Toggl_TimeEntryId old =
    case old of
        Evergreen.V17.Toggl.TimeEntryId p0 ->
            Evergreen.V19.Toggl.TimeEntryId p0


migrate_Toggl_TogglApiError : Evergreen.V17.Toggl.TogglApiError -> Evergreen.V19.Toggl.TogglApiError
migrate_Toggl_TogglApiError old =
    case old of
        Evergreen.V17.Toggl.HttpError p0 ->
            Evergreen.V19.Toggl.HttpError p0

        Evergreen.V17.Toggl.RateLimited p0 ->
            Evergreen.V19.Toggl.RateLimited p0


migrate_Toggl_TogglProject : Evergreen.V17.Toggl.TogglProject -> Evergreen.V19.Toggl.TogglProject
migrate_Toggl_TogglProject old =
    { id = old.id |> migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , color = old.color
    }


migrate_Toggl_TogglProjectId : Evergreen.V17.Toggl.TogglProjectId -> Evergreen.V19.Toggl.TogglProjectId
migrate_Toggl_TogglProjectId old =
    case old of
        Evergreen.V17.Toggl.TogglProjectId p0 ->
            Evergreen.V19.Toggl.TogglProjectId p0


migrate_Toggl_TogglWorkspace : Evergreen.V17.Toggl.TogglWorkspace -> Evergreen.V19.Toggl.TogglWorkspace
migrate_Toggl_TogglWorkspace old =
    { id = old.id |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , organizationId = old.organizationId
    }


migrate_Toggl_TogglWorkspaceId : Evergreen.V17.Toggl.TogglWorkspaceId -> Evergreen.V19.Toggl.TogglWorkspaceId
migrate_Toggl_TogglWorkspaceId old =
    case old of
        Evergreen.V17.Toggl.TogglWorkspaceId p0 ->
            Evergreen.V19.Toggl.TogglWorkspaceId p0


migrate_Toggl_WebhookPayload : Evergreen.V17.Toggl.WebhookPayload -> Evergreen.V19.Toggl.WebhookPayload
migrate_Toggl_WebhookPayload old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Types_BackendMsg : Evergreen.V17.Types.BackendMsg -> Evergreen.V19.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V17.Types.NoOpBackendMsg ->
            Evergreen.V19.Types.NoOpBackendMsg

        Evergreen.V17.Types.ClientConnected p0 p1 ->
            Evergreen.V19.Types.ClientConnected p0 p1

        Evergreen.V17.Types.ClientDisconnected p0 p1 ->
            Evergreen.V19.Types.ClientDisconnected p0 p1

        Evergreen.V17.Types.GotTogglWorkspaces p0 p1 ->
            Evergreen.V19.Types.GotTogglWorkspaces p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V17.Types.GotTogglProjects p0 p1 ->
            Evergreen.V19.Types.GotTogglProjects p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V17.Types.GotTogglTimeEntries p0 p1 p2 p3 p4 p5 ->
            Evergreen.V19.Types.GotTogglTimeEntries p0
                (p1 |> migrate_Types_CalendarInfo)
                (p2 |> migrate_Toggl_TogglWorkspaceId)
                (p3 |> migrate_Toggl_TogglProjectId)
                p4
                (p5 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TimeEntry))

        Evergreen.V17.Types.GotWebhookValidation p0 ->
            Evergreen.V19.Types.GotWebhookValidation p0

        Evergreen.V17.Types.GotStopTimerResponse p0 p1 ->
            Evergreen.V19.Types.GotStopTimerResponse p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError)

        Evergreen.V17.Types.BroadcastRunningEntry p0 ->
            Evergreen.V19.Types.BroadcastRunningEntry (p0 |> migrate_Types_RunningEntry)

        Evergreen.V17.Types.CodaPollTick p0 ->
            -- CodaPollTick was renamed to MonofocusPollTick; same semantic.
            Evergreen.V19.Types.MonofocusPollTick p0

        Evergreen.V17.Types.GotCodaResponse _ ->
            -- An in-flight Coda HTTP response can't be decoded by the new Monofocus
            -- handler. Drop it; the 30-min poll will refetch from the new endpoint.
            Evergreen.V19.Types.NoOpBackendMsg

        Evergreen.V17.Types.StartTimerWithTime p0 p1 p2 ->
            Evergreen.V19.Types.StartTimerWithTime p0 p1 p2

        Evergreen.V17.Types.GotStartTimerResponse p0 p1 ->
            Evergreen.V19.Types.GotStartTimerResponse p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError)

        Evergreen.V17.Types.GotRpcStartTimerResponse p0 ->
            Evergreen.V19.Types.GotRpcStartTimerResponse p0


migrate_Types_CalendarInfo : Evergreen.V17.Types.CalendarInfo -> Evergreen.V19.Types.CalendarInfo
migrate_Types_CalendarInfo old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = old.isOrangetheory
    }


migrate_Types_CreateCalendarModal : Evergreen.V17.Types.CreateCalendarModal -> Evergreen.V19.Types.CreateCalendarModal
migrate_Types_CreateCalendarModal old =
    { selectedWorkspace = old.selectedWorkspace |> Maybe.map migrate_Toggl_TogglWorkspace
    , selectedProject = old.selectedProject |> Maybe.map migrate_Toggl_TogglProject
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = old.isOrangetheory
    , projectFilter = old.projectFilter
    }


migrate_Types_EditCalendarModal : Evergreen.V17.Types.EditCalendarModal -> Evergreen.V19.Types.EditCalendarModal
migrate_Types_EditCalendarModal old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , originalProjectId = old.originalProjectId |> migrate_Toggl_TogglProjectId
    , selectedWorkspace = old.selectedWorkspace |> migrate_Toggl_TogglWorkspace
    , selectedProject = old.selectedProject |> migrate_Toggl_TogglProject
    , calendarName = old.calendarName
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , isOrangetheory = old.isOrangetheory
    , projectFilter = old.projectFilter
    }


migrate_Types_ModalState : Evergreen.V17.Types.ModalState -> Evergreen.V19.Types.ModalState
migrate_Types_ModalState old =
    case old of
        Evergreen.V17.Types.ModalClosed ->
            Evergreen.V19.Types.ModalClosed

        Evergreen.V17.Types.ModalCreateCalendar p0 ->
            Evergreen.V19.Types.ModalCreateCalendar (p0 |> migrate_Types_CreateCalendarModal)

        Evergreen.V17.Types.ModalEditCalendar p0 ->
            Evergreen.V19.Types.ModalEditCalendar (p0 |> migrate_Types_EditCalendarModal)


migrate_Types_RunningEntry : Evergreen.V17.Types.RunningEntry -> Evergreen.V19.Types.RunningEntry
migrate_Types_RunningEntry old =
    case old of
        Evergreen.V17.Types.NoRunningEntry ->
            Evergreen.V19.Types.NoRunningEntry

        Evergreen.V17.Types.RunningEntry p0 ->
            Evergreen.V19.Types.RunningEntry (p0 |> migrate_Toggl_WebhookPayload)


migrate_Types_ToFrontend : Evergreen.V17.Types.ToFrontend -> Evergreen.V19.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V17.Types.NoOpToFrontend ->
            Evergreen.V19.Types.NoOpToFrontend

        Evergreen.V17.Types.CalendarsUpdated p0 ->
            Evergreen.V19.Types.CalendarsUpdated (p0 |> migrate_CalendarDict_CalendarDict)

        Evergreen.V17.Types.TogglWorkspacesReceived p0 ->
            Evergreen.V19.Types.TogglWorkspacesReceived (p0 |> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V17.Types.TogglProjectsReceived p0 ->
            Evergreen.V19.Types.TogglProjectsReceived (p0 |> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V17.Types.TogglTimeEntriesReceived p0 ->
            Evergreen.V19.Types.TogglTimeEntriesReceived (p0 |> Result.map (List.map migrate_Toggl_TimeEntry))

        Evergreen.V17.Types.RunningEntryUpdated p0 ->
            Evergreen.V19.Types.RunningEntryUpdated (p0 |> migrate_Types_RunningEntry)

        Evergreen.V17.Types.WebhookDebugEvent p0 ->
            Evergreen.V19.Types.WebhookDebugEvent (p0 |> migrate_Types_WebhookDebugEntry)

        Evergreen.V17.Types.WebhookEventsCleared ->
            Evergreen.V19.Types.WebhookEventsCleared

        Evergreen.V17.Types.StopTimerFailed p0 p1 ->
            Evergreen.V19.Types.StopTimerFailed p0 (p1 |> migrate_Types_RunningEntry)

        Evergreen.V17.Types.CodaStatusUpdated _ ->
            -- Old CodaStatus has a different shape; reset the frontend to
            -- "not fetched" so it pulls fresh state from the new backend poll.
            Evergreen.V19.Types.MonofocusStatusUpdated Evergreen.V19.Types.MonofocusNotFetched

        Evergreen.V17.Types.StartMonofocusTimerFailed p0 ->
            Evergreen.V19.Types.StartMonofocusTimerFailed p0


migrate_Types_TogglConnectionStatus : Evergreen.V17.Types.TogglConnectionStatus -> Evergreen.V19.Types.TogglConnectionStatus
migrate_Types_TogglConnectionStatus old =
    case old of
        Evergreen.V17.Types.NotConnected ->
            Evergreen.V19.Types.NotConnected

        Evergreen.V17.Types.Connecting ->
            Evergreen.V19.Types.Connecting

        Evergreen.V17.Types.Connected p0 ->
            Evergreen.V19.Types.Connected (p0 |> List.map migrate_Toggl_TogglWorkspace)

        Evergreen.V17.Types.ConnectionError p0 ->
            Evergreen.V19.Types.ConnectionError p0


migrate_Types_WebhookDebugEntry : Evergreen.V17.Types.WebhookDebugEntry -> Evergreen.V19.Types.WebhookDebugEntry
migrate_Types_WebhookDebugEntry old =
    old
