module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.CalendarDict
import Evergreen.V1.HabitCalendar
import Evergreen.V1.Toggl
import Evergreen.V1.Types
import Evergreen.V4.CalendarDict
import Evergreen.V4.HabitCalendar
import Evergreen.V4.Toggl
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Result
import SeqDict
import Time
import Toggl exposing (TogglWorkspaceId)


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V4.Types.BackendModel
migrate_Types_BackendModel old =
    { calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglWorkspaces = old.togglWorkspaces |> List.map migrate_Toggl_TogglWorkspace
    , togglProjects = old.togglProjects |> List.map migrate_Toggl_TogglProject
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    }


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentTime = old.currentTime
    , currentZone = old.currentZone
    , calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglStatus = old.togglStatus |> migrate_Types_TogglConnectionStatus
    , modalState = old.modalState |> migrate_Types_ModalState
    , availableProjects = old.availableProjects |> List.map migrate_Toggl_TogglProject
    , projectsLoading = old.projectsLoading
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    , webhookDebugLog = old.webhookDebugLog
    }


migrate_CalendarDict_CalendarDict : Evergreen.V1.CalendarDict.CalendarDict -> Evergreen.V4.CalendarDict.CalendarDict
migrate_CalendarDict_CalendarDict old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_HabitCalendar_HabitCalendarId migrate_HabitCalendar_HabitCalendar) |> SeqDict.fromList


migrate_HabitCalendar_HabitCalendar : Evergreen.V1.HabitCalendar.HabitCalendar -> Evergreen.V4.HabitCalendar.HabitCalendar
migrate_HabitCalendar_HabitCalendar old =
    { id = old.id |> migrate_HabitCalendar_HabitCalendarId
    , name = old.name
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , weeksShowing = old.weeksShowing
    , entries = old.entries
    , timeEntries = SeqDict.empty
    , timezone = Time.utc
    , workspaceId = Evergreen.V4.Toggl.TogglWorkspaceId 4150145
    , projectId = Evergreen.V4.Toggl.TogglProjectId 159657524
    }


migrate_HabitCalendar_HabitCalendarId : Evergreen.V1.HabitCalendar.HabitCalendarId -> Evergreen.V4.HabitCalendar.HabitCalendarId
migrate_HabitCalendar_HabitCalendarId old =
    case old of
        Evergreen.V1.HabitCalendar.HabitCalendarId p0 ->
            Evergreen.V4.HabitCalendar.HabitCalendarId p0


migrate_Toggl_TimeEntry : Evergreen.V1.Toggl.TimeEntry -> Evergreen.V4.Toggl.TimeEntry
migrate_Toggl_TimeEntry old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Toggl_TimeEntryId : Evergreen.V1.Toggl.TimeEntryId -> Evergreen.V4.Toggl.TimeEntryId
migrate_Toggl_TimeEntryId old =
    case old of
        Evergreen.V1.Toggl.TimeEntryId p0 ->
            Evergreen.V4.Toggl.TimeEntryId p0


migrate_Toggl_TogglApiError : Evergreen.V1.Toggl.TogglApiError -> Evergreen.V4.Toggl.TogglApiError
migrate_Toggl_TogglApiError old =
    case old of
        Evergreen.V1.Toggl.HttpError p0 ->
            Evergreen.V4.Toggl.HttpError p0

        Evergreen.V1.Toggl.RateLimited p0 ->
            Evergreen.V4.Toggl.RateLimited p0


migrate_Toggl_TogglProject : Evergreen.V1.Toggl.TogglProject -> Evergreen.V4.Toggl.TogglProject
migrate_Toggl_TogglProject old =
    { id = old.id |> migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , color = old.color
    }


migrate_Toggl_TogglProjectId : Evergreen.V1.Toggl.TogglProjectId -> Evergreen.V4.Toggl.TogglProjectId
migrate_Toggl_TogglProjectId old =
    case old of
        Evergreen.V1.Toggl.TogglProjectId p0 ->
            Evergreen.V4.Toggl.TogglProjectId p0


migrate_Toggl_TogglWorkspace : Evergreen.V1.Toggl.TogglWorkspace -> Evergreen.V4.Toggl.TogglWorkspace
migrate_Toggl_TogglWorkspace old =
    { id = old.id |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , organizationId = old.organizationId
    }


migrate_Toggl_TogglWorkspaceId : Evergreen.V1.Toggl.TogglWorkspaceId -> Evergreen.V4.Toggl.TogglWorkspaceId
migrate_Toggl_TogglWorkspaceId old =
    case old of
        Evergreen.V1.Toggl.TogglWorkspaceId p0 ->
            Evergreen.V4.Toggl.TogglWorkspaceId p0


migrate_Toggl_WebhookPayload : Evergreen.V1.Toggl.WebhookPayload -> Evergreen.V4.Toggl.WebhookPayload
migrate_Toggl_WebhookPayload old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Types_BackendMsg : Evergreen.V1.Types.BackendMsg -> Evergreen.V4.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V1.Types.NoOpBackendMsg ->
            Evergreen.V4.Types.NoOpBackendMsg

        Evergreen.V1.Types.ClientConnected p0 p1 ->
            Evergreen.V4.Types.ClientConnected p0 p1

        Evergreen.V1.Types.ClientDisconnected p0 p1 ->
            Evergreen.V4.Types.ClientDisconnected p0 p1

        Evergreen.V1.Types.GotTogglWorkspaces p0 p1 ->
            Evergreen.V4.Types.GotTogglWorkspaces p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V1.Types.GotTogglProjects p0 p1 ->
            Evergreen.V4.Types.GotTogglProjects p0
                (p1 |> Result.mapError migrate_Toggl_TogglApiError >> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V1.Types.GotTogglTimeEntries p0 p1 p2 p3 ->
            Evergreen.V4.Types.GotTogglTimeEntries p0
                (p1 |> migrate_Types_CalendarInfo)
                (p2 |> migrate_Toggl_TogglWorkspaceId)
                (p3 |> migrate_Toggl_TogglProjectId)
                (Unimplemented {- This new variant needs to be initialised -})
                (Unimplemented {- This new variant needs to be initialised -})

        Evergreen.V1.Types.GotWebhookValidation p0 ->
            Evergreen.V4.Types.GotWebhookValidation p0


migrate_Types_CalendarInfo : Evergreen.V1.Types.CalendarInfo -> Evergreen.V4.Types.CalendarInfo
migrate_Types_CalendarInfo old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , calendarName = old.calendarName
    }


migrate_Types_CreateCalendarModal : Evergreen.V1.Types.CreateCalendarModal -> Evergreen.V4.Types.CreateCalendarModal
migrate_Types_CreateCalendarModal old =
    { selectedWorkspace = old.selectedWorkspace |> Maybe.map migrate_Toggl_TogglWorkspace
    , selectedProject = old.selectedProject |> Maybe.map migrate_Toggl_TogglProject
    , calendarName = old.calendarName
    }


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V4.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V4.Types.UrlChanged p0

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg

        Evergreen.V1.Types.GotTime p0 ->
            Evergreen.V4.Types.GotTime p0

        Evergreen.V1.Types.GotZone p0 ->
            Evergreen.V4.Types.GotZone p0

        Evergreen.V1.Types.Tick p0 ->
            Evergreen.V4.Types.Tick p0

        Evergreen.V1.Types.RefreshWorkspaces ->
            Evergreen.V4.Types.RefreshWorkspaces

        Evergreen.V1.Types.OpenCreateCalendarModal ->
            Evergreen.V4.Types.OpenCreateCalendarModal

        Evergreen.V1.Types.CloseModal ->
            Evergreen.V4.Types.CloseModal

        Evergreen.V1.Types.SelectWorkspace p0 ->
            Evergreen.V4.Types.SelectWorkspace (p0 |> migrate_Toggl_TogglWorkspace)

        Evergreen.V1.Types.SelectProject p0 ->
            Evergreen.V4.Types.SelectProject (p0 |> migrate_Toggl_TogglProject)

        Evergreen.V1.Types.CalendarNameChanged p0 ->
            Evergreen.V4.Types.CalendarNameChanged p0

        Evergreen.V1.Types.SubmitCreateCalendar ->
            Evergreen.V4.Types.SubmitCreateCalendar

        notices ->
            {- @NOTICE `RefreshCalendar Evergreen.V4.HabitCalendar.HabitCalendarId Evergreen.V4.Toggl.TogglWorkspaceId Evergreen.V4.Toggl.TogglProjectId String` was added in V4.
               This is just a reminder in case migrating some subset of the old data to this new value was important.
               See https://dashboard.lamdera.app/tips/modified-custom-type for more info.
            -}
            (Unimplemented {- New constructors were added. I need you to resolve the above notices and then remove this case. -})


migrate_Types_ModalState : Evergreen.V1.Types.ModalState -> Evergreen.V4.Types.ModalState
migrate_Types_ModalState old =
    case old of
        Evergreen.V1.Types.ModalClosed ->
            Evergreen.V4.Types.ModalClosed

        Evergreen.V1.Types.ModalCreateCalendar p0 ->
            Evergreen.V4.Types.ModalCreateCalendar (p0 |> migrate_Types_CreateCalendarModal)


migrate_Types_RunningEntry : Evergreen.V1.Types.RunningEntry -> Evergreen.V4.Types.RunningEntry
migrate_Types_RunningEntry old =
    case old of
        Evergreen.V1.Types.NoRunningEntry ->
            Evergreen.V4.Types.NoRunningEntry

        Evergreen.V1.Types.RunningEntry p0 ->
            Evergreen.V4.Types.RunningEntry (p0 |> migrate_Toggl_WebhookPayload)


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V4.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.NoOpToFrontend ->
            Evergreen.V4.Types.NoOpToFrontend

        Evergreen.V1.Types.CalendarsUpdated p0 ->
            Evergreen.V4.Types.CalendarsUpdated (p0 |> migrate_CalendarDict_CalendarDict)

        Evergreen.V1.Types.TogglWorkspacesReceived p0 ->
            Evergreen.V4.Types.TogglWorkspacesReceived (p0 |> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V1.Types.TogglProjectsReceived p0 ->
            Evergreen.V4.Types.TogglProjectsReceived (p0 |> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V1.Types.TogglTimeEntriesReceived p0 ->
            Evergreen.V4.Types.TogglTimeEntriesReceived (p0 |> Result.map (List.map migrate_Toggl_TimeEntry))

        Evergreen.V1.Types.RunningEntryUpdated p0 ->
            Evergreen.V4.Types.RunningEntryUpdated (p0 |> migrate_Types_RunningEntry)

        Evergreen.V1.Types.WebhookDebugEvent p0 ->
            Evergreen.V4.Types.WebhookDebugEvent (p0 |> migrate_Types_WebhookDebugEntry)


migrate_Types_TogglConnectionStatus : Evergreen.V1.Types.TogglConnectionStatus -> Evergreen.V4.Types.TogglConnectionStatus
migrate_Types_TogglConnectionStatus old =
    case old of
        Evergreen.V1.Types.NotConnected ->
            Evergreen.V4.Types.NotConnected

        Evergreen.V1.Types.Connecting ->
            Evergreen.V4.Types.Connecting

        Evergreen.V1.Types.Connected p0 ->
            Evergreen.V4.Types.Connected (p0 |> List.map migrate_Toggl_TogglWorkspace)

        Evergreen.V1.Types.ConnectionError p0 ->
            Evergreen.V4.Types.ConnectionError p0


migrate_Types_WebhookDebugEntry : Evergreen.V1.Types.WebhookDebugEntry -> Evergreen.V4.Types.WebhookDebugEntry
migrate_Types_WebhookDebugEntry old =
    old
