module Evergreen.Migrate.V8 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V6.CalendarDict
import Evergreen.V6.HabitCalendar
import Evergreen.V6.Toggl
import Evergreen.V6.Types
import Evergreen.V8.CalendarDict
import Evergreen.V8.HabitCalendar
import Evergreen.V8.Toggl
import Evergreen.V8.Types
import Lamdera.Migrations exposing (ModelMigration(..), MsgMigration(..))
import SeqDict


frontendModel : Evergreen.V6.Types.FrontendModel -> ModelMigration Evergreen.V8.Types.FrontendModel Evergreen.V8.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V6.Types.BackendModel -> ModelMigration Evergreen.V8.Types.BackendModel Evergreen.V8.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V6.Types.FrontendMsg -> MsgMigration Evergreen.V8.Types.FrontendMsg Evergreen.V8.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V6.Types.ToBackend -> MsgMigration Evergreen.V8.Types.ToBackend Evergreen.V8.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V6.Types.BackendMsg -> MsgMigration Evergreen.V8.Types.BackendMsg Evergreen.V8.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V6.Types.ToFrontend -> MsgMigration Evergreen.V8.Types.ToFrontend Evergreen.V8.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V6.Types.BackendModel -> Evergreen.V8.Types.BackendModel
migrate_Types_BackendModel old =
    { calendars = old.calendars |> migrate_CalendarDict_CalendarDict
    , togglWorkspaces = old.togglWorkspaces |> List.map migrate_Toggl_TogglWorkspace
    , togglProjects = old.togglProjects |> List.map migrate_Toggl_TogglProject
    , runningEntry = old.runningEntry |> migrate_Types_RunningEntry
    , webhookEvents = [] -- Start with empty list on migration
    }


migrate_CalendarDict_CalendarDict : Evergreen.V6.CalendarDict.CalendarDict -> Evergreen.V8.CalendarDict.CalendarDict
migrate_CalendarDict_CalendarDict old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_HabitCalendar_HabitCalendarId migrate_HabitCalendar_HabitCalendar) |> SeqDict.fromList


migrate_HabitCalendar_HabitCalendar : Evergreen.V6.HabitCalendar.HabitCalendar -> Evergreen.V8.HabitCalendar.HabitCalendar
migrate_HabitCalendar_HabitCalendar old =
    { id = old.id |> migrate_HabitCalendar_HabitCalendarId
    , name = old.name
    , successColor = old.successColor
    , nonzeroColor = old.nonzeroColor
    , weeksShowing = old.weeksShowing
    , entries = old.entries
    , timeEntries = old.timeEntries |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Toggl_TimeEntryId migrate_Toggl_TimeEntry) |> SeqDict.fromList
    , timezone = old.timezone
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , projectId = old.projectId |> migrate_Toggl_TogglProjectId
    }


migrate_HabitCalendar_HabitCalendarId : Evergreen.V6.HabitCalendar.HabitCalendarId -> Evergreen.V8.HabitCalendar.HabitCalendarId
migrate_HabitCalendar_HabitCalendarId old =
    case old of
        Evergreen.V6.HabitCalendar.HabitCalendarId p0 ->
            Evergreen.V8.HabitCalendar.HabitCalendarId p0


migrate_Toggl_TimeEntry : Evergreen.V6.Toggl.TimeEntry -> Evergreen.V8.Toggl.TimeEntry
migrate_Toggl_TimeEntry old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Toggl_TimeEntryId : Evergreen.V6.Toggl.TimeEntryId -> Evergreen.V8.Toggl.TimeEntryId
migrate_Toggl_TimeEntryId old =
    case old of
        Evergreen.V6.Toggl.TimeEntryId p0 ->
            Evergreen.V8.Toggl.TimeEntryId p0


migrate_Toggl_TogglProject : Evergreen.V6.Toggl.TogglProject -> Evergreen.V8.Toggl.TogglProject
migrate_Toggl_TogglProject old =
    { id = old.id |> migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , color = old.color
    }


migrate_Toggl_TogglProjectId : Evergreen.V6.Toggl.TogglProjectId -> Evergreen.V8.Toggl.TogglProjectId
migrate_Toggl_TogglProjectId old =
    case old of
        Evergreen.V6.Toggl.TogglProjectId p0 ->
            Evergreen.V8.Toggl.TogglProjectId p0


migrate_Toggl_TogglWorkspace : Evergreen.V6.Toggl.TogglWorkspace -> Evergreen.V8.Toggl.TogglWorkspace
migrate_Toggl_TogglWorkspace old =
    { id = old.id |> migrate_Toggl_TogglWorkspaceId
    , name = old.name
    , organizationId = old.organizationId
    }


migrate_Toggl_TogglWorkspaceId : Evergreen.V6.Toggl.TogglWorkspaceId -> Evergreen.V8.Toggl.TogglWorkspaceId
migrate_Toggl_TogglWorkspaceId old =
    case old of
        Evergreen.V6.Toggl.TogglWorkspaceId p0 ->
            Evergreen.V8.Toggl.TogglWorkspaceId p0


migrate_Toggl_WebhookPayload : Evergreen.V6.Toggl.WebhookPayload -> Evergreen.V8.Toggl.WebhookPayload
migrate_Toggl_WebhookPayload old =
    { id = old.id |> migrate_Toggl_TimeEntryId
    , projectId = old.projectId |> Maybe.map migrate_Toggl_TogglProjectId
    , workspaceId = old.workspaceId |> migrate_Toggl_TogglWorkspaceId
    , description = old.description
    , start = old.start
    , stop = old.stop
    , duration = old.duration
    }


migrate_Types_CalendarInfo : Evergreen.V6.Types.CalendarInfo -> Evergreen.V8.Types.CalendarInfo
migrate_Types_CalendarInfo old =
    { calendarId = old.calendarId |> migrate_HabitCalendar_HabitCalendarId
    , calendarName = old.calendarName
    }


migrate_Types_FrontendMsg : Evergreen.V6.Types.FrontendMsg -> Evergreen.V8.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V6.Types.UrlClicked p0 ->
            Evergreen.V8.Types.UrlClicked p0

        Evergreen.V6.Types.UrlChanged p0 ->
            Evergreen.V8.Types.UrlChanged p0

        Evergreen.V6.Types.NoOpFrontendMsg ->
            Evergreen.V8.Types.NoOpFrontendMsg

        Evergreen.V6.Types.GotTime p0 ->
            Evergreen.V8.Types.GotTime p0

        Evergreen.V6.Types.GotZone p0 ->
            Evergreen.V8.Types.GotZone p0

        Evergreen.V6.Types.Tick p0 ->
            Evergreen.V8.Types.Tick p0

        Evergreen.V6.Types.RefreshWorkspaces ->
            Evergreen.V8.Types.RefreshWorkspaces

        Evergreen.V6.Types.RefreshCalendar p0 p1 p2 p3 ->
            Evergreen.V8.Types.RefreshCalendar (p0 |> migrate_HabitCalendar_HabitCalendarId)
                (p1 |> migrate_Toggl_TogglWorkspaceId)
                (p2 |> migrate_Toggl_TogglProjectId)
                p3

        Evergreen.V6.Types.OpenCreateCalendarModal ->
            Evergreen.V8.Types.OpenCreateCalendarModal

        Evergreen.V6.Types.CloseModal ->
            Evergreen.V8.Types.CloseModal

        Evergreen.V6.Types.SelectWorkspace p0 ->
            Evergreen.V8.Types.SelectWorkspace (p0 |> migrate_Toggl_TogglWorkspace)

        Evergreen.V6.Types.SelectProject p0 ->
            Evergreen.V8.Types.SelectProject (p0 |> migrate_Toggl_TogglProject)

        Evergreen.V6.Types.CalendarNameChanged p0 ->
            Evergreen.V8.Types.CalendarNameChanged p0

        Evergreen.V6.Types.SubmitCreateCalendar ->
            Evergreen.V8.Types.SubmitCreateCalendar

        Evergreen.V6.Types.StopRunningTimer ->
            Evergreen.V8.Types.StopRunningTimer

        Evergreen.V6.Types.DismissStopTimerError ->
            Evergreen.V8.Types.DismissStopTimerError


migrate_Types_RunningEntry : Evergreen.V6.Types.RunningEntry -> Evergreen.V8.Types.RunningEntry
migrate_Types_RunningEntry old =
    case old of
        Evergreen.V6.Types.NoRunningEntry ->
            Evergreen.V8.Types.NoRunningEntry

        Evergreen.V6.Types.RunningEntry p0 ->
            Evergreen.V8.Types.RunningEntry (p0 |> migrate_Toggl_WebhookPayload)


migrate_Types_ToBackend : Evergreen.V6.Types.ToBackend -> Evergreen.V8.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V6.Types.NoOpToBackend ->
            Evergreen.V8.Types.NoOpToBackend

        Evergreen.V6.Types.RequestCalendars ->
            Evergreen.V8.Types.RequestCalendars

        Evergreen.V6.Types.FetchTogglWorkspaces ->
            Evergreen.V8.Types.FetchTogglWorkspaces

        Evergreen.V6.Types.FetchTogglProjects p0 ->
            Evergreen.V8.Types.FetchTogglProjects (p0 |> migrate_Toggl_TogglWorkspaceId)

        Evergreen.V6.Types.FetchTogglTimeEntries p0 p1 p2 p3 p4 p5 ->
            Evergreen.V8.Types.FetchTogglTimeEntries (p0 |> migrate_Types_CalendarInfo)
                (p1 |> migrate_Toggl_TogglWorkspaceId)
                (p2 |> migrate_Toggl_TogglProjectId)
                p3
                p4
                p5

        Evergreen.V6.Types.StopTogglTimer p0 p1 ->
            Evergreen.V8.Types.StopTogglTimer (p0 |> migrate_Toggl_TogglWorkspaceId)
                (p1 |> migrate_Toggl_TimeEntryId)


migrate_Types_ToFrontend : Evergreen.V6.Types.ToFrontend -> Evergreen.V8.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V6.Types.NoOpToFrontend ->
            Evergreen.V8.Types.NoOpToFrontend

        Evergreen.V6.Types.CalendarsUpdated p0 ->
            Evergreen.V8.Types.CalendarsUpdated (p0 |> migrate_CalendarDict_CalendarDict)

        Evergreen.V6.Types.TogglWorkspacesReceived p0 ->
            Evergreen.V8.Types.TogglWorkspacesReceived (p0 |> Result.map (List.map migrate_Toggl_TogglWorkspace))

        Evergreen.V6.Types.TogglProjectsReceived p0 ->
            Evergreen.V8.Types.TogglProjectsReceived (p0 |> Result.map (List.map migrate_Toggl_TogglProject))

        Evergreen.V6.Types.TogglTimeEntriesReceived p0 ->
            Evergreen.V8.Types.TogglTimeEntriesReceived (p0 |> Result.map (List.map migrate_Toggl_TimeEntry))

        Evergreen.V6.Types.RunningEntryUpdated p0 ->
            Evergreen.V8.Types.RunningEntryUpdated (p0 |> migrate_Types_RunningEntry)

        Evergreen.V6.Types.WebhookDebugEvent p0 ->
            Evergreen.V8.Types.WebhookDebugEvent (p0 |> migrate_Types_WebhookDebugEntry)

        Evergreen.V6.Types.StopTimerFailed p0 p1 ->
            Evergreen.V8.Types.StopTimerFailed p0 (p1 |> migrate_Types_RunningEntry)


migrate_Types_WebhookDebugEntry : Evergreen.V6.Types.WebhookDebugEntry -> Evergreen.V8.Types.WebhookDebugEntry
migrate_Types_WebhookDebugEntry old =
    old
